In [ ]:
import pandas as pd
import numpy as np
ser_2 = pd.Series([1,-1,2,-3,-5], index=['a','b','c','d','e'])
ser_2

a    1
b   -1
c    2
d   -3
e   -5
dtype: int64

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
index = ['foo','bar','baz','qux']
ser_A= pd.Series(dict_1, index = index)
ser_A

foo    100.0
bar    200.0
baz    300.0
qux      NaN
dtype: float64

In [13]:
data_1= {'state':['VA','VA','VA','MD','MD'],
         'year':[2012,2013,2014,2014,2015],
         'pop':[5.0,5.1,5.2,4.0,4.1]}
df_1 = pd.DataFrame(data_1)
df_1

  state  year  pop
0    VA  2012  5.0
1    VA  2013  5.1
2    VA  2014  5.2
3    MD  2014  4.0
4    MD  2015  4.1

In [15]:
del df_3('state_dup')
df_3

SyntaxError: cannot delete function call (<ipython-input-15-585b8c2dc001>, line 1)

In [19]:
# WAP in python to print the series of prime numbers from 1 to 300?
for i in range(1,301):
    for j in range(2,i):
        if i%j==0:
            break

    else:
        print(i)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293

In [21]:
import pandas as pd

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def primes_up_to_300():
    primes = []
    for num in range(1, 301):
        if is_prime(num):
            primes.append(num)
    return primes

prime_numbers = primes_up_to_300()
df = pd.DataFrame(prime_numbers, columns=["Prime Numbers"])

print(df)

    Prime Numbers
0               2
1               3
2               5
3               7
4              11
..            ...
57            271
58            277
59            281
60            283
61            293

[62 rows x 1 columns]

In [22]:
import pandas as pd

def generate_fibonacci(max_value):
    fib_series = [0, 1]

    while True:
        next_value = fib_series[-1] + fib_series[-2]
        if next_value > max_value:
            break
        fib_series.append(next_value)

    fib_series = [num for num in fib_series if num >= 1]

    return fib_series
max_value = 100

fib_series = generate_fibonacci(max_value)
df = pd.DataFrame(fib_series, columns=["Fibonacci Numbers"])

print(df)

    Fibonacci Numbers
0                   1
1                   1
2                   2
3                   3
4                   5
5                   8
6                  13
7                  21
8                  34
9                  55
10                 89

WAP IN python to add all the numbers in the list and find maximum and minimum,
input the number from user and ?

In [26]:
def calculate_sum(numbers):
    total = 0
    for number in numbers:
        total += number
    return total

def find_maximum(numbers):
    max_num = numbers[0]
    for number in numbers:
        if number > max_num:
            max_num = number
    return max_num

def find_minimum(numbers):
    min_num = numbers[0]
    for number in numbers:
        if number < min_num:
            min_num = number
    return min_num
user_input = input("Enter numbers separated by spaces: ")
numbers = [int(num) for num in user_input.split()]

sum_of_numbers = calculate_sum(numbers)
maximum_number = find_maximum(numbers)
minimum_number = find_minimum(numbers)
print("SUM OF NUMBERS: ")
print(sum_of_numbers)
print("MAXIMUM NUMBER: ")
print(maximum_number)
print("MINIMUM NUMBER: ")
print(minimum_number)

Enter numbers separated by spaces: 12 43 54 123 56 231 4
SUM OF NUMBERS:
523
MAXIMUM NUMBER:
231
MINIMUM NUMBER:
4